<h3>The <?php echo Yii::app()->name ?> API</h3>
<p>Integrate <?php echo Yii::app()->name ?> into your application.  The API allows you to programatically access and save bookmarks.</p>

<h4>Authentication</h4>
<p>The <?php echo Yii::app()->name ?> API uses token authentication.  Each API request requires a user token.  The token can be generated by the user on <a class="blue" href="<?php echo $this->createUrl('index/key') ?>">this page</a>. Your application should provide the user instructions on how they can generate a token.</p>

<h4>Create a Bookmark</h4>
<h5 class="endpoint"><?php echo $this->createAbsoluteUrl('api/create') ?></h5>
<span class="label success radius methods">POST</span>
<h6 class="params">Parameters</h6>
<p>token : string user token </p>
<p>url: a valid url  </p>
<p>title: String (optional) </p>
<p>list: String (optional) </p>

<h4>Delete a Bookmark</h4>
<h5 class="endpoint"><?php echo $this->createAbsoluteUrl('api/delete') ?></h5>
<span class="label success radius methods">POST</span>
<h6 class="params">Parameters</h6>
<p>token : string user token </p>
<p>bk_id: a bookmark id  </p>

<h4>Retrieve Bookmarks</h4>
<h5 class="endpoint"><?php echo $this->createAbsoluteUrl('api/get') ?></h5>
<span class="label success radius methods">GET</span>
<h6 class="params">Parameters</h6>
<p>token : string user token </p>
<p>from: a unix timestamp (optional) </p>
<p>to: a unix timestamp (optional) </p>
<p>limit: integer (optional)  <i>This will limit the number of bookmarks retrieved at a time</i></p> 	

<h4>Retrieve Bookmarks from List</h4>
<h5 class="endpoint"><?php echo $this->createAbsoluteUrl('api/get') ?>/<span class="blue">{List Name Goes Here}</span></h5>
<span class="label success radius methods">GET</span>
<h6 class="params">Parameters</h6>
<p>token : string user token </p>
<p>from: a unix timestamp (optional) </p>
<p>to: a unix timestamp (optional) </p>
<p>limit: integer (optional) <i>This will limit the number of bookmarks retrieved at a time</i></p>

<h4>Retrieve Lists</h4>
<h5 class="endpoint"><?php echo $this->createAbsoluteUrl('api/lists') ?></h5>
<span class="label success radius methods">GET</span>
<h6 class="params">Parameters</h6>
<p>token : string user token </p>